### ISSUE TITLE
Figure out supported browser versions

### ISSUE THREAD

**Issue by pdehaan** [mozilla/send#101]
We should decide on a list of supported browsers/versions and add that to the README so we know what features we can use and what we'll need to polyfill.

- Chrome?
- Safari?
- Opera?

**Comment by dannycoates** [comment]
Supported browsers/versions is limited by support for GCM encryption (unfortunately this excludes mobile safari). We've got a function that checks compatibility that can trigger the unsupported ui https://github.com/mozilla/testpilot-assets/tree/master/File_Transfer/Send_11_support

![unsupported](https://github.com/mozilla/testpilot-assets/blob/master/File_Transfer/Send_11_support/preview/page-1-support.png?raw=true)

**Comment by dannycoates** [comment]
Since GCM is the limiting factor we don't need any polyfills for anything we're using. Closing this as nothing left to do

**Comment by pdehaan** [comment]
Not sure if this is the correct link, but is http://caniuse.com/#feat=cryptography saying that we can get Safari support using the `crypto.webkitSubtle` prefix?

**Comment by pdehaan** [comment]
Doh, nevermind. Searching `webkitSubtle` gives me #56 where you mentioned all this before.

**Comment by pdehaan** [comment]
But original comment still stands. Having a definitive list of supported browsers would be super useful for testing and figuring out the autoprefixer matrix.

Also, it'd be nice to start a GitHub FAQ.md with a "Why isn't my browser supported?" question which outlines the GCM comments above. Bonus points if we add a little "Why?" link to the mockup above so users can go directly from the "Your browser is not supported" page to the FAQ answer.

**Comment by grahamperrin** [comment]
Found: 

- https://github.com/mozilla/send/blob/master/docs/faq.md#why-is-my-browser-not-supported

– but it took a few minutes, and a little knowledge of GitHub, for me to find that page. Prior to searching, I more than half-expected to find a suitably prominent link both: 

- from the main page <https://send.firefox.com/>; and 
- from <https://testpilot.firefox.com/experiments/send>.

I assume that there's orientation, to the answers, _only if_ someone aims to send or receive with an unsupported browser. 

> https://github.com/mozilla/testpilot-assets/tree/master/File_Transfer/Send_11_support

Not found, I guess that it was superseded by something. 

If – for example – I want to send something to a colleague or friend without knowing whether  their iPhone is modern enough, then (I feel) there's there's the ridiculous situation of attempting to correlate e.g. <http://caniuse.com/#feat=cryptography> with <https://en.wikipedia.org/wiki/IOS_10> and then asking the prospective recipient whether it's likely to work because when I scroll down to <https://en.wikipedia.org/wiki/IOS_10#Supported_devices> the array of data means _very_ little to me (and I'm IT-literate) simply because I switched to Android, from a first generation iPhone, around three years ago.

**Comment by grahamperrin** [comment]
## Plain English (or locale)

In lieu of: 

> You can use Send in any modern browser.

… something like: 

> You can use Send in any modern browser. 
> 
> Recipients using Android or iOS should be fine if their device is less than _n_ years old.

**Comment by ehuggett** [comment]
A polyfill for gcm mode was introduced in https://github.com/mozilla/send/commit/2dfbee090a6848f367a30deb1e41cb2adb11b3a7 (so it may no longer be the limiting factor, https://github.com/PeculiarVentures/webcrypto-liner/blob/master/BrowserSupport.md ).

> Recipients using Android or iOS should be fine if their device is less than n years old.Recipients using Android or iOS should be fine if their device is less than n years old.

Its difficult to make blanket statements about Android devices. I've only just stopped using a Samsung S2 from 2011, It would definitely have worked with Send because I had  installed Firefox, perhaps users with chrome installed by default will also always be up to date? (does it update from google play? I've never had it installed on Android).

Technically "modern browser" also covers mobile devices, perhaps we should link these words to getfirefox.com 😄
