### ISSUE TITLE
[Send v2] The “Open with” pop-up is wrongly displayed immediately after the “Download” button was clicked

### ISSUE THREAD

**Issue by Softvision-AndreeaCupsa** [mozilla/send#1118]
**[Notes]:**
- This issue is not reproducible on Firefox 64. Considering this, using the mozregression tool I have found the issue that broke this in Beta and Nightly. Here is the pushlog: https://tinyurl.com/y97pz33w

**[Affected Versions]:**
- Firefox 65 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux 

**[Prerequisites]**
- Have a valid link to a file uploaded through the [Send V2 website](https://send2.dev.lcip.org/). 

**[Steps to reproduce]:**
1. Open the Firefox Browser and navigate to the link from the prerequisites. 
2. Click the download button and observe the behavior. 

**[Expected result]:**
- The “Open with” pop-up is displayed only after the download is complete.

**[Actual result]:**
- As soon as the progress bar starts showing progress the “Open with” pop-up is displayed.

**[Additional Notes]:**
- This issue is not reproducible with “javascript.options.streams” pref set to “false”.
- Attached a screen recording with the issue:

![rec of issue - regression](https://user-images.githubusercontent.com/37875464/51611736-a8a43f00-1f28-11e9-8fe7-0a94bee03566.gif)

**Comment by dannycoates** [comment]
Isn't this how the download dialog normally works, i.e. not on Send?

**Comment by SoftVision-CosminMuntean** [comment]
Andreea is on PTO so I will try to respond instead of her.

Yes, in most of the cases this is how the download dialog works. But Andreea logged this issue because on the Send website the download dialog used to be displayed only after the download was completed. Considering this she investigated this behavior and found the following information:

- If you are using Firefox 64 and you download a file from Send v2 website you can observe that the download dialog is displayed only after the file is completed downloaded.
- If you are using Firefox 65 or above, the behavior is changed. The download dialog is displayed right after you click the "Download" button. Considering this, using mozregression tool, Andreea found out that this change was introduce by [bug 1389628](https://bugzilla.mozilla.org/show_bug.cgi?id=1389628) in Firefox 65.
However, if you set the "javascript.options.streams" pref set to "false" on Firefox 65 or above, on the Send website the download dialog is displayed only after the download is completed.

- Also, on the [Send v1 website](https://send.firefox.com/), the download dialog is displayed only after the download is completed on all Firefox versions. So only the Send v2 website is affected.

**Comment by dannycoates** [comment]
Thanks @Softvision-AndreeaCupsa and @SoftVision-CosminMuntean 

The desired behavior in vnext is for the dialog to show immediately. We display the dialog later for browsers that don't enable streams for backward compatibility.
