### ISSUE TITLE
Download links are indexed by google search engine

### ISSUE THREAD

**Issue by marniepw** [mozilla/send#1250]
See: [https://twitter.com/unkn0wn_p3rson/status/1106070555071901696](https://twitter.com/unkn0wn_p3rson/status/1106070555071901696)

@firefox Firefox Send is awesome, but the download links are indexed by google search engine, can't download the original content becoz of expiry, but name of the files available in google search engine, seems noindex, robots meta tag missed cc : @TheHackersNews

**Comment by jbuck** [comment]
I've started the DNS verification dance with Google Search Console so that I can manually delete results, but [Google says](https://support.google.com/webmasters/answer/93710) we need to remove the robots.txt Disallow rule, and add `<meta name="robots" content="noindex">` to the download page to remove results permanently

**Comment by dannycoates** [comment]
fixed in v3.0.6
