### ISSUE TITLE
Typo in French legal page chiffrés vs cryptés

### ISSUE THREAD

**Issue by Oumph** [mozilla/send#1253]
Legal page doesn't seem to be taken from this git repo. But anyway:

in Mozilla Send repo, the right French translation is used (files are "chiffrés", not "cryptés"):

> ./public/locales/fr/send.ftl:introDescription = { -send-brand } vous permet de partager des fichiers **chiffrés** (...)
> ./public/locales/fr/send.ftl:notifyUploadEncryptDone = Votre fichier est **chiffré** (...)

On legal page https://www.mozilla.org/fr/about/legal/terms/services/#send

> (e) Firefox Send vous permet de partager des fichiers **cryptés**

**Comment by pdehaan** [comment]
The legal page seems to be in the **mozilla/legal-docs** repo at https://github.com/mozilla/legal-docs/blame/master/firefox_cloud_services_ToS/fr.md#L39

I _think_ this bug is saying that our local repo is correct and the upstream **legal-docs** is incorrect. If that sounds right, I can file this upstream.

/cc @flodolo

**Comment by flodolo** [comment]
CC @TheoChevalier 
The legal doc is translated by vendors, improvements should be filed there (not sure who owns that repo these days).

**Comment by TheoChevalier** [comment]
I can confirm “cryptés” is a blatant mistake and that the latest update in the legal-docs repo needs improvements. Right now it’s not adhering to the styleguide, nor using the UI terminology. I can offer some review next week and file an issue upstream

**Comment by peiying2** [comment]
@TheoChevalier pls comment in the legal doc, and I will pass it on to the vendor. There are quite a few updates lately and if you notice style changes (due to resource availability) or it has been constantly bad, I will ask for a change of translator. Has there been anyone decent or has it always been bad for French?

**Comment by pdehaan** [comment]
Filed upstream in the **legal-docs** repo as https://github.com/mozilla/legal-docs/issues/1243.

Thanks everybody! Pleasure as always. ❤️
