### ISSUE TITLE
Firefox Send login results in "Something went wrong!" screen

### ISSUE THREAD

**Issue by SuffolkPunch** [mozilla/send#1267]
I'm trying Firefox Send in Firefox 65.0.1 (64 bit) running in Linux Mint 18.3 (Cinnamon 64-bit).

What I do:
1. In Firefox goto https://send.firefox.com and click on Sign in/Up
2. Enter my Firefox Account password and click 'Sign in/Up'
3. The 'Sign in Continue to Firefox Send' page is displayed with the correct email address. Enter my Firefox Account password and click 'Sign in'.
4. A screen is displayed with the error message "Something went wrong!"  - see attached file.
![firefox-send-error](https://user-images.githubusercontent.com/26813480/54676884-a0681a80-4af9-11e9-959a-41aa5f517d3a.jpg)

I don't get this problem when I use Firefox 66 in Windows 7.

**Comment by johngruen** [comment]
@SuffolkPunch can you take a screenshot of your browser's JS console?

**Comment by SuffolkPunch** [comment]
@johngruen  I will if you tell me how.  In FF65 I see I can open the browser console (Ctrl+Shift+J) or the web console (Ctrl+Shift+K).  Are those what you want to see?

**Comment by dannycoates** [comment]
Thanks @SuffolkPunch, web console is all we need. Anything in there that shows up as red will be helpful.

**Comment by SuffolkPunch** [comment]
I can't get FF to trip the previous error! My apologies - i feel a fraud!

Anyway (with the following FF add-ons enabled: DuckDuckGo Privacy Essentials, LastPass, Noscript, Privacy Badger) , here is a snapshot of the jsconsole for the first of the 2 Firefox-Send login screens (email address entry):

![jsconsole-1 sign in up screen](https://user-images.githubusercontent.com/26813480/54785667-b7545d00-4c1e-11e9-8431-93a67182d281.jpg)
And here is the snapshot of jsconsole for the second login screen (password entry)
![jsconsole-2-after entering FF-send password successfully](https://user-images.githubusercontent.com/26813480/54785671-ba4f4d80-4c1e-11e9-8482-a28a4b1a22e6.jpg)



Martin

**Comment by dannycoates** [comment]
Thanks @SuffolkPunch! I still believe you :) We may have fixed your original issue with another release before your second attempt. I'm glad it's working for you now.

**Comment by J-J-Chiarella** [comment]
Please re-open this.

Ubuntu 19.04 (x86-64). Firefox 68.0
Add-ons: uBlock Origin, HTTPS Everywhere, Zotero
Other notables: I am logged into Firefox Sync on two devices.

I get the "something went wrong" screen on <https://send.firefox.com>. I get an e-mail every time, however, indicating I (successfully) signed in to Firefox Send at [TIME]. I have tried Private Window and that made no difference.

**Comment by wls** [comment]
**Firefox 77.0** (64-bit) / maxOS Mojave 10.14.6 -- Still happening

![Screen Shot 2020-06-11 at 11 33 40 PM](https://user-images.githubusercontent.com/537381/84462152-468ecb80-ac3c-11ea-9870-2c7464319da8.png)

The following happens when first visiting the site:

```
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). 2
Error in parsing value for ‘-webkit-text-size-adjust’.  Declaration dropped. app.fb202a2a.css:1:107
```

Able to login with username, password, drag the file, set the days and duration, and submit the upload form. The progress bar appears for a moment, and then these errors and the above "something went wrong" screen:

```
error { target: FileReader, isTrusted: true, lengthComputable: true, loaded: 0, total: 65536, srcElement: FileReader, eventPhase: 0, bubbles: false, cancelable: false, returnValue: true, … }
controller.js:183:16
Error: connection closed api.js:16:4
```
​
**Failing Code's `try` Block**

![Screen Shot 2020-06-11 at 11 49 50 PM](https://user-images.githubusercontent.com/537381/84463111-c28a1300-ac3e-11ea-84c1-b08d4382f7e6.png)

**Extensions**

- uBlock Origin installed, but disabled for this site
- Ghostery installed, but paused
- NoScript installed, but allows the whole of ...firefox.com
- EFF Privacy badger installed, but disabled for this site

![Screen Shot 2020-06-11 at 11 44 08 PM](https://user-images.githubusercontent.com/537381/84463151-dafa2d80-ac3e-11ea-8040-010e1e11d6e0.png)

- Problem happens even when all extensions are disabled

![Screen Shot 2020-06-12 at 12 00 17 AM](https://user-images.githubusercontent.com/537381/84463512-06314c80-ac40-11ea-856d-8505396b22ff.png)

**Firefox Settings**

- Firefox set for Standard blocking, Always "Do Not Track" and Delete cookies and site data when Firefox is closed
- Firefox set for https://send.firefox.com/ to Always be allowed to write cookies


![Screen Shot 2020-06-11 at 11 41 16 PM](https://user-images.githubusercontent.com/537381/84462528-4b07b400-ac3d-11ea-9340-56c5f4415157.png)

![Screen Shot 2020-06-11 at 11 41 56 PM](https://user-images.githubusercontent.com/537381/84462540-4e9b3b00-ac3d-11ea-9ad6-26ff1af23fe0.png)


**Little Snitch**
- Allow any incoming
- Allow only outgoing to port 80 and 443

![Screen Shot 2020-06-11 at 11 58 03 PM](https://user-images.githubusercontent.com/537381/84463366-8c995e80-ac3f-11ea-9820-e3c266798735.png)
