### ISSUE TITLE
Upload not working in Safari when NODE_ENV is set to production

### ISSUE THREAD

**Issue by davidweizheng** [mozilla/send#1483]
I have NODE_ENV set to production. It works fine in Chrome. However in Safari, it shows "Something went wrong!" when uploading file. Safari Developer console shows this error:
```
[Error] Refused to connect to wss://<my-site>/api/ws because it does not appear in the connect-src directive of the Content Security Policy.
```

It seems working fine in both Safari and Chrome if NODE_ENV is set to development.

Any idea?

**Comment by fzzzy** [comment]
If you use production, I think you'll have to change the domain name hardcoded in the code to be your domain. The send server is adding the csp header which points at our server and that's why the request is blocked, as seen by the error.

Sorry, I don't remember exactly where this is set. Try looking at the value of the csp header and searching for the string of the domain in the code.

**Comment by davidweizheng** [comment]
Thanks @fzzzy 

Confirmed it's working in Safari once I added my site to this location
https://github.com/mozilla/send/blob/master/server/routes/index.js#L42

**Comment by fzzzy** [comment]
🎉
