### ISSUE TITLE
Verify file upload sizes

### ISSUE THREAD

**Issue by clouserw** [mozilla/send#170]
Sounds like there are some inconsistencies across browsers when uploading files.  Can we double check that modern/popular browsers can upload 2G files? /cc @SoftVision-CiprianMuresan

**Comment by SoftVision-PaulOiegas** [comment]
Sure thing! We'll do that on Monday morning, almost everyone left the office already. 😃

**Comment by SoftVision-CiprianMuresan** [comment]
I've got some preliminary results because I've used archives containing dummy files in order to get to ~2GB to test the scenarios below. 
I'll continue investigating this using large video files.

**Windows 10 x64**:
Chrome 59.0.3071.115 (Official Build) (64-bit) - Crashes when I try to upload a file larger than 1 GB, works as expected with a 512MB file.
Nightly 56 x64 Build ID 20170709030204 - Takes a loooong time to show that it's uploading the 2 GB file (#128).
Firefox Release, Beta & Nightly (x32) do not start uploading a 1 GB file (#95).
Waiting for the new designs to be implemented in order to test Edge and Internet Explorer (see #127).
Opera - OOM crash when trying to upload a 2GB file (unsure if it was on the list of supported browsers)

**Windows 10 x32**:
Chrome - Crashes when trying to upload a 1GB file.
Nightly - Upload does not start (1GB file).
IE & Edge - Waiting for designs.

**Ubuntu 14.04 x64**:
Chrome - Crashes when trying to upload a 2GB file, works with 1GB file.
Nightly - Upload starts when trying to upload a 2GB file, but if I try with a 2.1GB file then the upload does not start.

**Mac 10.12**:
Chrome - Crashes when I try to upload a 2GB (2.15 GB to be exact) file, but works as expected with a 1GB file.
Safari - Upload doesn't seem to start when trying to upload a 1GB file.
Nightly - Takes a long time to start uploading a 1GB file, doesn't seem to work with a 2GB file.

**Comment by SoftVision-CiprianMuresan** [comment]
I did my second round of testing using 3 .mp4 files:
- File 1 - 1.75 GB (1,888,898,157 bytes) 
- File 2 - 1.93 GB (2,083,051,872 bytes)
- File 3 - 2.02 GB (2,176,408,828 bytes) 
(File sizes as seen by Windows; Mac and Linux do a better job at this 😆)

I might just reiterate my comment above, but we can never be too sure. Also I've intentionally left out IE and Edge because they're not working yet. I'll revisit these scenarios when the new UI lands.

**Windows 10 x64**:
Nightly 56 - Upload starts for Files 1 & 2; Error message appears for File 3.
Firefox 54 x32 - Upload does not start for File 1; Error message appears for Files 2 & 3.
Chrome - Crashes when trying to upload Files 1, 2 & 3. 

**Windows 10 x32**:
Firefox 54 & Nightly 56 - Error message appears when trying to upload Files 1, 2 & 3.
Chrome - Crashes when trying to upload Files 1, 2 & 3.

**Mac 10.12**:
Nightly 56 - Upload starts for Files 1 & 2; Error message appears for File 3.
Firefox 54 - Upload starts for Files 1 & 2; Error message appears for File 3.
Chrome - Upload starts for File 1 & 2; Crashes when trying to upload File 3.
Safari - I had to use the Stage version of the site, because Safari does not support gcm encryption which is needed for Dev version; Upload does not start for Files 1, 2 & 3.

**Ubuntu 14.04 x64**:
Firefox 54 - Upload starts for Files 1 & 2; Error message appears for File 3.
Nightly 56 - Error message appears when trying to upload Files 1, 2 & 3.
Chrome - Crashes when trying to upload Files 1, 2 & 3.

**Ubuntu 12.04 x32**:
Firefox 54 & Nightly 56 - Error message appears when trying to upload Files 1, 2 & 3.

Let me know if there's something more I can do.

**Comment by abhinadduri** [comment]
Microsoft Edge performs terribly with upload times as the file sizes increase:


Size (MB) | Time (ms)
-- | --
16.31 | 1041
32.63 | 4472
48.94 | 10774
65.26 | 20369
81.57 | 30459
97.89 | 49753
114.2 | 67604
212.09 | 266042
396.3 | 917797
525.96 | 1889461

The 525.96 file upload does not actually finish; it fails after decrypting the file.

**Comment by dannycoates** [comment]
I think we have the data we need. Thanks all!
