### ISSUE TITLE
QA launch signoff

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#22]
Placeholder for QA signoff of v1 release

**Comment by pdehaan** [comment]
FWIW, I ran my local link checker against stage+prod and only got a few [expected] errors and warnings:

<img width="1440" alt="integrity_v6" src="https://user-images.githubusercontent.com/557895/28685515-ebe23ab6-72bc-11e7-8b79-53cf0489276d.png">

The errors were basically the l20n's use of `{locale}` in the URL, so nothing of note there. The remaining 404s were just because the experiment pages haven't landed in Test Pilot prod yet, so any links to the Send experiment will be busted.

As for the warnings, they are all the regular old Mozilla 301's to the locale pages (so mozilla.org doing  a 301 redirect to mozilla.org/en-US/).
