### ISSUE TITLE
"Browser not supported" page is not displayed for older Firefox versions

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#319]
[Notes]:
- We should also show this page for Internet Explorer as long as we plan on releasing without support for it.
- Seeing as Test Pilot is not supported on Firefox 49 and lower, we should show this page on these versions.
- Opening the page on Safari correctly shows the "Browser not supported" page.

[Affected versions]:
- Firefox 49.0 and down

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Open the an old version of Firefox (49 or lower) and navigate to https://send.dev.mozaws.net/.
2. Observe the page.

[Expected result]:
- "Browser not supported" page is displayed.

[Actual results]:
- The page's UI is broken.

[Additional notes]:
- Here is a screen recording with the issue:
![browser not supported](https://user-images.githubusercontent.com/18304511/28623859-dfaa567c-721f-11e7-98a8-28c7443dcd92.gif)

**Comment by SoftVision-CosminMuntean** [comment]
It seems that we have a regression here. This issue is now reproducible on dev and stage server. 
The "Browser not supported" page is no longer displayed on Firefox 49 and below. However, the UI is correctly displayed on older versions of Firefox (<49), but the upload/download is not working. 

Here is screen recording with the issue:
![browser not supported](https://user-images.githubusercontent.com/19226534/30376522-6039680a-9895-11e7-968b-7bf4ed7ce6cd.gif)

**Comment by SoftVision-CosminMuntean** [comment]
This issue is still reproducible on all Send servers, but the behavior is changed. If you navigate to the Send page, the "https://send.stage.mozaws.net/unsupported/outdated" link is correctly displayed but the "Browser not supported" page is displayed only if the page is refreshed.

Here is a screen recording with the issue:
![browser unsuported at refresh](https://user-images.githubusercontent.com/19226534/31503118-75878964-af77-11e7-9a66-b37facee31f5.gif)

**Comment by johngruen** [comment]
Boy, this feels wontfixy

**Comment by johngruen** [comment]
will look at metrics
