### ISSUE TITLE
Use HTTP/2

### ISSUE THREAD

**Issue by digitarald** [mozilla/send#390]
Should speed up delivery of the many SVG files.

**Comment by pdehaan** [comment]
You can see this using the [Google Lighthouse tool](https://developers.google.com/web/tools/lighthouse/) as well:

<img width="1130" alt="lighthouse_report" src="https://user-images.githubusercontent.com/557895/28888811-d588e62a-7776-11e7-880f-fd2df410e1ba.png">

**Figure 1:** Production.

---

<img width="1125" alt="lighthouse_report_and_configuration" src="https://user-images.githubusercontent.com/557895/28888885-1179929c-7777-11e7-8e0b-199a65a8d990.png">

**Figure 2:** Dev server. 

You can see that the numbers are mostly the same, although the dev server currently gets a "Performance" score of 87 (versus 84 on production), which I think is because the dev server was arbitrarily ~300ms faster on render.

**Comment by akuckartz** [comment]
How was this resolved?

**Comment by jbuck** [comment]
@akuckartz put send behind a load balancer that supports nginx (Application Load Balanacer in AWS, Google Load Balancer in GCP)
