### ISSUE TITLE
Fira is only used for unsupported-browser message

### ISSUE THREAD

**Issue by digitarald** [mozilla/send#391]
Cutting the custom font download could cut down load time and remove the extraneous `fira.css`.

**Comment by pdehaan** [comment]
Possibly related to #278; _"Lazy load some assets"_.

**Comment by pdehaan** [comment]
Actually, since Fira seems to only be used on the `/unsupported/:reason` page(s), the easiest solution would be to move that `<link rel="stylesheet" href="https://code.cdn.mozilla.net/fonts/fira.css">` tag into the [/views/unsupported.handlebars](https://github.com/mozilla/send/blob/master/views/unsupported.handlebars) view.

Although it is not ideal to put a stylesheet in the body, so maybe there is a way we can include it in the `<head>` based on some Handlebars view variable/helper.
