### ISSUE TITLE
40-bit upload id may be subject to collision 

### ISSUE THREAD

**Issue by jepler** [mozilla/send#445]
In `server/server.js`, each upload is given an ID as follows:
~~~~
app.post('/upload', (req, res, next) => {
  const newId = crypto.randomBytes(5).toString('hex');
~~~~
According to the formula at https://en.wikipedia.org/wiki/Birthday_attack storing around 15,000 uploads leads to a 0.1% chance of two unformly chosen IDs being equal.

It appears that the consequence of `upload` choosing an ID that was already in use would be to overwrite the older upload, preventing that older upload from ever being downloaded successfully.

Increasing the size of the ID even slightly (e.g., to 7 random bytes / 14 hex digits) makes the chance of a collision much smaller (e.g., 1 in a million for 380,000 uploads).

Alternately, `upload` could check via `storage.exists` if the ID is already in use, and allocate a new ID if it is.  This would change the period of time in which a collision could occur from "the entire time from start of upload to start of download" to only "from the start of upload to the end of upload".  A server that has 15,000 uploads a day doesn't seem unlikely, but a server which has 15,000 uploads in progress at the same moment seems much less likely.

**Comment by ehuggett** [comment]
The length (character count) of the current ID in the url can be kept while also increasing the entropy by using a more efficient encoding (seems desirable for aesthetics to not make the url any larger than required).  If i found the correct [documentation](https://nodejs.org/docs/latest/api/buffer.html#buffer_buffer), toString can output url safe base64 ie

```const newId = crypto.randomBytes(7).toString('base64');```

Will result in 10 characters (the current length, once the padding/"=" characters are stripped off) while also reducing the risk of a collision as described by jepler.

(this works because base64 stores 7 bits per character, hex encoding results in 4 bits per character).

note: the decryption key in the link is already unpadded url safe base64

**Comment by johngruen** [comment]
This is a good point, but we're not near this scale atm. Would be nice though. We'll extend the length as soon as it's close to necessary.

**Comment by jepler** [comment]
@dannycoates Can you clarify why this issue was closed?  The problem I outline seems to continue to exist, though it is now at `server/routes/upload.js`.

**Comment by dannycoates** [comment]
An errant checkbox while closing multiple other issues... This will be fixed at the same time we increase the expiration time.

**Comment by dannycoates** [comment]
increased to 8 bytes in 8cf3b89f
