### ISSUE TITLE
Cannot access "Select file to upload button" using keyboard

### ISSUE THREAD

**Issue by sevaan** [mozilla/send#563]
The button to upload a file is not accessible via the keyboard...but should be!

**Comment by ehuggett** [comment]
The current method sets display:none on the form input and styles the label, this works because form labels redirect click events to input specified by the "for" attribute. Unfortunately, a label is not something the browser will let us tab too and we've hidden the button we could have tabbed too (Has anyone tried to use Send with a screen reader? )

This change hides the input button without using display:none, https://github.com/ehuggett/send/commit/c1e8424e679f91424c0f6e051132353bb4f62d93 and so you can tab to the upload button _**but without any kind of visual indication that the "button" (the label) has focus.**_

To give visual feedback we need to detect when the input button has focus. `input[type="file"]:focus` seems to work in chromium but not [Firefox](https://bugzilla.mozilla.org/buglist.cgi?quicksearch=input+file+focus), the event can however be caught in javascript so a workaround would be
 
```javascript
// https://tympanus.net/codrops/2015/09/15/styling-customizing-file-inputs-smart-way/
input.addEventListener( 'focus', function(){ input.classList.add( 'has-focus' ); });
input.addEventListener( 'blur', function(){ input.classList.remove( 'has-focus' ); });
```

I think we should also use the tabindex attribute https://www.w3.org/TR/html5/editing.html#attr-tabindex to make the upload button first in the tabbing order?

**Comment by ehuggett** [comment]
I'm not sure the current transition from `#0297f8` to `#0287e8` used for the (mouse) :hover event is suitable by itself for visual feedback with the (keyboard) :focus event as its too subtle.

I think we should apply the standard/expected dotted outline for a button to the label, even if the dotted outline applied to the upload-window div may distract from this.

**Comment by johngruen** [comment]
@sevaan we might want a specific focus state for the buttons. care to propose something?

**Comment by ehuggett** [comment]
I've included the js from the same article the css came from in https://github.com/ehuggett/send/tree/tab-upload and it seems to work ok (inline script, as i wasn't sure where best to include it)

**Comment by sevaan** [comment]
> I think we should apply the standard/expected dotted outline for a button to the label, even if the dotted outline applied to the upload-window div may distract from this.

I like this solution and see it commonly used around the web. The colour should change to the active #0287e8 when focus is on the label.

**Comment by ehuggett** [comment]
The button itself or the dotted outline?

**Comment by sevaan** [comment]
Example:

![slice](https://user-images.githubusercontent.com/473531/30447567-85ac6a18-995a-11e7-98b2-6b29ed11e555.png)

**Comment by ehuggett** [comment]
(I think you just replied to a incomplete comment i made by accident and then deleted? Thanks for clarifying)

What i have is very close, but the keyboard focus outline is applied to the button and not the text
```
input[type="file"].has-focus + #browse,
input[type="file"]:focus + #browse {
  background-color: #0287e8;
  outline: 1px dotted #000;
  outline: -webkit-focus-ring-color auto 5px;
 }
```
But despite 'Highlight' being marked as deprecated in https://www.w3.org/TR/css3-color/#css-system , I was thinking about changing this so that gecko/firefox would also use the system style. i.e
```
input[type="file"].has-focus + #browse,
input[type="file"]:focus + #browse {
  background-color: #0287e8;
  outline: 1px dotted #000;
  outline: 1px dotted Highlight;
  outline: -webkit-focus-ring-color auto 5px;
 }
```

I'm not sure using system colours for the highlight makes sense as not using system colours for the button itself and they might clash (example: KDE seems to set a Blue very close to the Send button for the System Highlight colour, which will make it hard to see). In that case it would be

```
input[type="file"].has-focus + #browse,
input[type="file"]:focus + #browse {
  background-color: #0287e8;
  outline: 1px dotted #000;
}
```
Resulting in
![upload_button](https://user-images.githubusercontent.com/8090731/30450755-d28e2b80-9989-11e7-9a44-42b1655bc0a7.png)

**Comment by sevaan** [comment]
That looks great, ehuggett!

**Comment by ehuggett** [comment]
- I've moved the JS into dragManager, if this seems OK the file should probably be renamed.
- I have set the tabindex on the download button
- I tried to add tabindex on the upload link page (share.js), but strangely it resulted in not being able to tab to either the text or the copy to clipboard button
- rebased on master

Any other changes? I'll open a PR after having another bash at setting the tabindex for the link over the weekend

**Comment by ehuggett** [comment]
It seems positive tabindex values [may do more harm than good](http://adrianroselli.com/2014/11/dont-use-tabindex-greater-than-0.html), while I like the most useful element on the page receiving focus first the resulting tab navigation order is somewhat confusing

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA appears to be the appropriate method for making Send more accessible (separate issue?)

I'm going to make a few minor changes (incl removing the tabindex's) and then open a PR

**Comment by johngruen** [comment]
There's an open PR for this @ericawright can provide review!
