### ISSUE TITLE
Remaining password UI bits

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#587]
There's a few remaining things from the design spec that aren't done and some areas where I intentionally didn't follow the spec that should be reviewed. https://mozilla.invisionapp.com/share/CTDDQDXME#/screens/252367497

### Differences
- The 'add password' input box is plain text so the dots for the placeholder seemed to imply the text would be hidden or was already set to something. I changed it to 'Password'.
- I changed the label of the button from 'Submit' to 'Unlock'
- I took a few liberties with the strings

### Incomplete
- [x] responsive password input boxes
- [x] styled checkbox
- [x] "When the user clicks the "Require a password" checkbox, the link field is not disabled." --- it should be
- [x] "Try again?" should be "Try again."
- [x] Update checkbox style to match the preferences pane (see screenshot in comment below)

**Comment by ericawright** [comment]
> I changed the label of the button from 'Submit' to 'Unlock'
Nice change!

**Comment by Softvision-CristinaBadescu** [comment]
Hello,

I've went through the mock-ups in order to write test cases for password functionality and I've observed certain differences between the mock-ups and the experiment on dev server. For example:
- The "edit password" mode doesn't exists at the moment.
- When user checks box, the link field is not disabled.
- The title is different from the mock-ups: "The link to your file will expire after 1 download or in 24 hours." instead of "This encrypted link will expire after 1 download or in 24 hours".
- When typing a wrong password, the text has another punctuation: "Try again?" instead of "Try again:".

I strongly recommend using a hidden password instead of a plain text. Also, the user should have a "show/hide" option for the password when typing it; in this way some security issues can be avoided.
 
Are we going to implement these on the next release? If yes, I can log them so it will be easier to track.

**Comment by wresuolc** [comment]
Thanks for the feedback.  Replying to your bullet points:

- We're not planning on putting an 'edit password' mode in at this point
- This sounds like a bug, thanks for finding it.  I'll add that to the original post
- We think the one we have already translated is ok
- Thanks for finding this too.  I'll update that in the original post as well.

The password is hidden when entering the password when downloading a file, but we don't think it's necessary when creating the password and keeps the UI simpler (eg. don't have to enter twice).  Sevaan did some research on this.

**Comment by Softvision-CristinaBadescu** [comment]
Hello,

Thanks for your reply. Also, do you think I should file separately the issues in order to track them or is it sufficient that you included them in the original post?

**Comment by youwenliang** [comment]
@dannycoates A few couple things about the UI:

1. The styled checkbox can follow the checkboxes in Preference
![image](https://user-images.githubusercontent.com/8919308/31700378-82e03aba-b3fb-11e7-87b8-695224c88b82.png)

2. The password input field should align left with other components
![image](https://user-images.githubusercontent.com/8919308/31700393-a98dc7a4-b3fb-11e7-9ff1-6386edfde5c8.png)

**Comment by wresuolc** [comment]
Thanks!  I'll add the first to the original post.  The second is tracked at https://github.com/mozilla/send/issues/594

**Comment by Softvision-CristinaBadescu** [comment]
During testing I have encountered another scenario that seems a bit off. When a user checkes the "Require password..." checbox, his/her intention is to write a password. In order to do that the user must do two actions: 1-check the password checkbox, 2-click inside the password field. 
This behaviour could be more simpler and resume it to only 1 action. The password field should be autofocused after the user checks the "Require password..." checbox. From our perspective this will improve the UX.

What do you think about this proposal?

**Comment by ericawright** [comment]
@Softvision-CristinaBadescu I like it, and I agree.

**Comment by Pekochen** [comment]
[Send_password.zip](https://github.com/mozilla/send/files/1401546/Send_password.zip)
Hi, We found that something is not consistent with other pages and also we would like to sync photon style.
so I slightly revise a little bit some details, please see attached file for measurement. 
Thanks for your help : )
