### ISSUE TITLE
Drop deprecated CSP headers

### ISSUE THREAD

**Issue by wresuolc** [mozilla/send#627]
> $ curl -I https://send.firefox.com
> Content-Security-Policy: connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com; img-src 'self' https://www.google-analytics.com; script-src 'self'; style-src 'self' https://code.cdn.mozilla.net; font-src 'self' https://code.cdn.mozilla.net; form-action 'none'; frame-ancestors 'none'; object-src 'none'; report-uri /__cspreport__
> X-Content-Security-Policy: connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com; img-src 'self' https://www.google-analytics.com; script-src 'self'; style-src 'self' https://code.cdn.mozilla.net; font-src 'self' https://code.cdn.mozilla.net; form-action 'none'; frame-ancestors 'none'; object-src 'none'; report-uri /__cspreport__
> X-WebKit-CSP: connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com; img-src 'self' https://www.google-analytics.com; script-src 'self'; style-src 'self' https://code.cdn.mozilla.net; font-src 'self' https://code.cdn.mozilla.net; form-action 'none'; frame-ancestors 'none'; object-src 'none'; report-uri /__cspreport__
> [...]

The first header is good.  The other two are long over.

**Comment by ehuggett** [comment]
I fetched the headers from `https://send.firefox.com` with Firefox Developer Edition 57.0b13 (64-bit) and only the first was included (copied and pasted in full from "raw headers" in the dev console)
```http
Content-Security-Policy: connect-src 'self' https://sentry.prod.mozaws.net https://www.google-analytics.com; img-src 'self' https://www.google-analytics.com; script-src 'self'; style-src 'self' https://code.cdn.mozilla.net; font-src 'self' https://code.cdn.mozilla.net; form-action 'none'; frame-ancestors 'none'; object-src 'none'; report-uri /__cspreport__
Date: Thu, 02 Nov 2017 23:30:38 GMT
ETag: W/"148f-0wPB8eJIl/W3OrJk1iacUxMxJ3k"
Public-Key-Pins: max-age=86400; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="r/mIkG3eEpVdm+u/ko/cwxzOMo1bk4TyHIlByibiA5E="; pin-sha256="YLh1dUR9y6Kja30RrAn7JKnbQG/uEtLMkBgFF2Fuihg="; pin-sha256="sRHdihwgkaib1P1gxX8HFszlD+7/gTfNvuAybgLPNis=";
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Cached: MISS
X-Content-Type-Options: nosniff
X-DNS-Prefetch-Control: off
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
Connection: keep-alive
```

I Think the headers are being set by "helmet" as a fallback behaviour for an "unknown" browser, as I can see all 3 with `curl -I` and `wget --server-response`. https://github.com/helmetjs/csp/blob/0c82388831a481809b9b8f6e34b056786acbc03a/lib/get-header-keys-for-browser.js#L106 (lines above show how different browsers are handled, config.allHeaders is indeed [all 3 headers](https://github.com/helmetjs/csp/blob/010245afc9a2aa95cea11eddc8fcbb6ce6563107/lib/config.json#L39) )

Do you still want to do this? If so disabling browser detection should prevent the other two from ever being sent https://helmetjs.github.io/docs/csp/#browser-sniffing . But note in some cases helmet-csp deliberately sends no header (to avoid bugs caused by broken implementations perhaps? not sure)

**Comment by wresuolc** [comment]
Ah.  I mean, it's not a big deal, I just noticed it when curl'ing for those other issues.  I guess it could be a problem if we ever enable more aggressive caching and browsers start getting cached results from other browsers

**Comment by dannycoates** [comment]
I think we should just let `helmet` do its thing.

**Comment by wresuolc** [comment]
👍 thanks for the explanation @ehuggett
