### ISSUE TITLE
Verify reason for stopped events

### ISSUE THREAD

**Issue by johngruen** [mozilla/send#656]
confirm that this fires when fatal errors happen when `reason transfer stopped` is an error

**Comment by shikhar-scs** [comment]
@johngruen If you could be a bit more clear, I could work on this.

**Comment by dannycoates** [comment]
@shikhar-scs this is more of a Mozilla internal accounting thing, not a code thing.

**Comment by shikhar-scs** [comment]
Oh :+1:

**Comment by dannycoates** [comment]
Ok, so the `upload-stopped` and `download-stopped` events that have reason `errored` all look like genuine errors. 

Some of them were suspicious because the error was `ProgressEvent` which doesn't seem right for an error. However I found that Chrome will sometimes throw this as an error if it runs out of memory while loading the file with `FileReader`.
