### ISSUE TITLE
[Enhancement] Show number of remaining downloads

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#661]
[Affected versions]:
- Firefox 57.0 and up

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Steps to reproduce]:
1. Start the Firefox browser with and navigate to "https://send.stage.mozaws.net/" page.
2. Upload a file and set it to expire after 20 downloads.
3. Navigate to the homepage and observe the newly uploaded file in the file info table.

[Expected result]:
- The number of remaining downloads is displayed in the table.

[Actual results]:
- No such information is displayed.

[Notes]:
- This information could also be displayed on the file's download page.

**Comment by shikhar-scs** [comment]
@SoftVision-CiprianMuresan I am working on this. Though I had a doubt.
Do we need the information of `after downloads` to be dynamic ( i.e. that it should decrease after every download ) or not.

**Comment by sevaan** [comment]
> Do we need the information of after downloads to be dynamic ( i.e. should it decrease after every download ) or not.

Yes, that's correct. It's a running tally of how many downloads are left.

On the home page, please let's change the "Expires In" header to "Time" and add a column to the right with the header "Downloads". The number in the download column should be center aligned.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/473531/34275226-521e2ad0-e66a-11e7-99e3-0fafe38db900.png">

I feel like those last columns could be crushed to the right so that more of the file name shows.

**Comment by shikhar-scs** [comment]
@sevaan I've made the required changes and also have filed a PR #681 . Please review.

**Comment by sevaan** [comment]
I don't do code reviews, I'm afraid. My programming skills are lacking. @dannycoates do you mind taking a look?

**Comment by shikhar-scs** [comment]
@dannycoates Yes Please
