### ISSUE TITLE
Restrict the banner from showing on unsupported browsers

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#663]
[Notes]:
- Since the Download Firefox page is already displayed instead, we could do without the banner showing.

[Affected versions]:
- Firefox 57.0 and up

[Affected Platforms]:
- All Windows

[Steps to reproduce]:
1. Start the Edge browser with and navigate to "https://send.dev.mozaws.net/" page.
2. Observe the top part of the page.

[Expected result]:
- The download banner is not displayed.

[Actual results]:
- The download banner is displayed.

[Additional Notes]:
- Here is a screen recording with the issue:
![img_08122017_150638_0](https://user-images.githubusercontent.com/18304511/33767904-903e6a5c-dc2c-11e7-943e-ff781e04c8df.png)

**Comment by BrunoScheufler** [comment]
I tried to reproduce it with Edge multiple times but the header didn't show up for me 😕 Does it still show up for you? I'm really curious about this know.

**Comment by Softvision-CristinaBadescu** [comment]
Hello @BrunoScheufler ,
I've managed to reproduce this issue using Microsoft Edge 40.15063.674.0 on Windows 10x64, using English (United States) Language and US keyboard layout. Can you please provide the version of the Microsoft Edge you are using and also the set language and keyboard? Maybe due to this setting you didn't encounter this issue.
Below you can see a screenshot with the issue:
![send microsoft edge](https://user-images.githubusercontent.com/31244235/33876044-f66554d2-df2c-11e7-8ee5-14be66f34e23.png)

**Comment by BrunoScheufler** [comment]
Hello @Softvision-CristinaBadescu ,
I've tried again using Win10 (1709) using the German language and German/DE keyboard layout. The header did not show up for me in any of the tests, that might be because of the language or some other factor. It looks like this to me:
![edge](https://user-images.githubusercontent.com/4772980/33892730-d3720e02-df59-11e7-8026-b7d6042fc70e.png)

**Comment by dannycoates** [comment]
The banner is en-US only for now

**Comment by BrunoScheufler** [comment]
@dannycoates well that explains it all, thank you 🙂

**Comment by johngruen** [comment]
stretch!

**Comment by himanish-star** [comment]
I would like to work on this issue . May I ?

**Comment by dannycoates** [comment]
@himanish-star yes. The way I recommend approaching it is to check `state.route` in `app/routes/index.js` and not render the `fxPromo` if it equals `'/unsupported/:reason'`

**Comment by himanish-star** [comment]
Ok , Sure I'll keep this in mind while fixing it.
