### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#68]

**Comment by wresuolc** [comment]
Let's do this!  @relud says he will have stage up by the end of this week and we can test on there.  /cc @pdehaan

**Comment by relud** [comment]
stage is live at https://fileshare.stage.mozaws.net

**Comment by pdehaan** [comment]
@dannycoates ~~What's the general flow happening here?~~ Nevermind, I see you outlined this in https://github.com/mozilla/something-awesome/issues/128#issuecomment-310792463:

> 1. _Loading the file from disk into Firefox_
> 1. _Hashing the file (not in master yet)_
> 1. _Encrypting the file_

If we want to run the load tests through our current stack (Molotov/Ardere), we'd need to have a couple test cases written in Python.
First we'd need to figure out Python versions of the client side loading/hashing/encrypting or whatever. Or maybe we already have some sample payloads which we just POST to the server and our upload test just randomly chooses one of the 3-4 pre-encrypted payloads (1KB file, 10KB file, 100KB file, 1MB file?) to send off to the server.

For load testing, did we have any ideas apart from:

1. Uploading files to S3/Redis.
1. Uploading a file once and then viewing file download page for an existing upload X times.

I was trying to think of the use case of load testing a file upload and download in the same test, but not sure how valuable that'd be since you can only download a file once.

**Comment by pdehaan** [comment]
From our **#testpilot-p2p** Slack channel:

### ----- June 27th, 2017 -----

**clouserw** [4:59 PM] 
> @relud @pdehaan and I were thinking about load testing this project
> we're doing so little on the server, it feels like we're mostly just passing through to s3
> so any load testing we're doing just ends up load testing s3 or redis

**relud** [5:00 PM] 
> i mean, the load test could prove it
> and show how far we can go with the current redis

**clouserw** [5:01 PM] 
> so you think it's valuable to run a test?
> an upload/download test, or just hitting redis over and over
> I guess I'm wondering at what point we're just hitting the amazon limits we pay for

### ----- June 28th, 2017 -----

**clouserw** [9:25 AM]:
> @relud what do you think an effective load test looks like?  Uploading a bunch of small files?
> downloading only happens once, so that doesn't really seem like it's worth testing

**relud** [9:56 AM] 
> @clouserw I think we should do a load test with both uploads and downloads running at the same time, with a mix of small and medium requests, to show that the application can perform under load. My biggest concern for this application is that it will be completely io bound, which means that I can't scale on cpu, and I will need to scale on network throughput.

**clouserw** [9:57 AM] 
> I think that's a valid concern.  it probably will be I/O bound

**pdehaan** [9:59 AM] 
> yeah, that sounds like a good plan. Since files can only be downloaded once. It seems like we can easily do a test which uploads a file then tries downloading that file, and then see how many times it can do that in, say, 5 minutes.

**Comment by wresuolc** [comment]
800r/s found, we never hit auto-scaling.  Thanks!
