### ISSUE TITLE
Encrypt filename

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#69]

**Comment by ehuggett** [comment]
and now the content-type? (added in #489 )

I had a bash at learning enough JavaScript just to attempt to encrypt the filenames the other day. Lets just say both it and my knowledge of JavaScript still need a lot of work... 😆 

https://github.com/ehuggett/send/commit/170c0470887de499f82adf980d63fc9cf9e35674
- It now conflicts with master
- Doesn't decrypt filename for display on download page (just for the save as filename). The key object is not currently created until the file decryption stage (and now we need crypto available an a much earlier stage)
- Reuses the IV, I think we should consider deriving both IV's from the current one instead of sending another? (there is an open issue for RFC 8188, something similar to [Section 2.3](https://tools.ietf.org/html/rfc8188#section-2.3)?)
