### ISSUE TITLE
The set password is wrongly changed to 5 bullets after the Link copy page is refreshed

### ISSUE THREAD

**Issue by SoftVision-CiprianMuresan** [mozilla/send#752]
[Affected versions]:
- Firefox 58.0 and up

[Affected Platforms]:
- All Windows
- All Linux
- All Mac

[Steps to reproduce]:
1. Start the browser and navigate to "https://send.stage.mozaws.net/" page.
2. Upload a file and set a password.
3. Refresh the page and hover the password.

[Expected result]:
- The set password is displayed.

[Actual results]:
- 5 bullets are displayed.

[Notes]:
- The issue is also reproducible on the Dev server.
- The issue is also reproducible if the file page is opened in a new tab from the File info table.
- Here is a screen recording with the issue:
![password changes to 5 bullets after the link copy page is refreshed](https://user-images.githubusercontent.com/18304511/35814231-394cbc26-0a9e-11e8-8109-b6ef5c906ba0.gif)

**Comment by dannycoates** [comment]
I forgot to mention this in the release notes, sorry. This is intentional in order to stop saving the password in local storage (#688). We might be able to improve the UI to make it more clear though. I did it this way to start because it was the smallest change that worked.

If someone forgets their password they can still change it to a new one.
