### ISSUE TITLE
Uploading broken with Firefox Nightly

### ISSUE THREAD

**Issue by dannycoates** [mozilla/send#836]
On at least OSX uploading a file over ~2mb fails. The upload xhr connects to the server but fails to send any data, eventually timing out.

**Comment by timvisee** [comment]
Can confirm, got the same issue on Linux with Nightly. The file doesn't upload, nor does the upload indicator go further than 0 bytes.

Details:
- Firefox: `62.0a1 (2018-05-31) (64-bit)`
- OS: `Linux Ubuntu 17.10`

**Comment by dannycoates** [comment]
It's working again for me as of `2018-06-01`

**Comment by SoftVision-CiprianMuresan** [comment]
So I did a bit of digging around for this issue and it seems our Prod, Stage and Dev versions of the website were affected after [bug 1434553](https://bugzilla.mozilla.org/show_bug.cgi?id=1434553) was fixed. 
It's working again because of the follow-up [bug 1464090](https://bugzilla.mozilla.org/show_bug.cgi?id=1464090).

This was a Nightly only issue and it is no longer reproducible. @dannycoates, I think we can close this one based on this information.
