### ISSUE TITLE
Support sharing file to multiple people

### ISSUE THREAD

**Issue by marco-c** [mozilla/send#98]
Sometimes you need to share a file to multiple people (e.g. a vacation album). A limit of 1 download doesn't work in this case, it would be useful to provide a way to select the number of maximum downloads.

(Also, if you are sharing to multiple users, it would be great if all users could upload what they have, like bittorrent, but this is out of scope for this issue).

**Comment by ehuggett** [comment]
May i suggest the download limit is kept low enough, if not kept at 1,  to prevent the service becoming popular for mass distribution of content someone might object to (or claim only they have exclusive right to distribute). The 24 hour expiry might be enough in itself to discourage this, the combination of both seems very effective even if it was not intended to be.

If the limit was increased, Would it be sensible to prevent one recipient from downloading the file repeatedly (accidentally or otherwise) and triggering the deletion of the 'shared' data when the maximum number of downloads is reached?

**Comment by dannycoates** [comment]
The single, expiring download is very intentional. Thanks for your thoughts. Finding a good balance for increasing limits is important.

**Comment by michael-dev** [comment]
Having limit=1 (and not some other small constant) avoids the argument of "replication" of material, which is sometimes protected by law.

**Comment by wresuolc** [comment]
This exists now
